# 
# This is the default CodeQL configuration, which
# should work for this project.
#
name: "PyLint"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '13 9 * * 1'

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    
    steps: 
      - name: pylint3-action
        uses: LakshitF/pylint3-action@v2
        with:
          filename: check_zfs.py
