# 
# This is the default CodeQL configuration, which
# should work for this project.
#
name: "PyLint"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '13 9 * * 1'

jobs:
  lint:
    name: pylint3-action
    # You may pin to the exact commit or the version.
    # uses: LakshitF/pylint3-action@f9ac408de536e64f63009a439a92e0fb9a614941
    uses: LakshitF/pylint3-action@v2
    with:
      filename: check_zfs.py
